#!/bin/bash

args=("$@")

cd "$(dirname "$(find / -type f -name termbgcolors 2> /dev/null)")"

./schemer2 -format img::urxvt -in ${args[0]} -out colors

feh --bg-fill ${args[0]} >> log
python gentermcolors.py ~/.Xdefaults colors outf

mv outf $HOME/.Xdefaults

rm ./colors
